### ISSUE TITLE
Finalise the idea for FB AI hackathon

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#1]
I went to the facebook hackathon [website](https://fbai2.devpost.com/?ref_content=online-hackathons&ref_feature=challenge&ref_medium=facebook-channel) and now I remember the scope:

>Build AI natural language interactions with Wit.ai
>submit a solution featuring natural language interactions that leverage the Wit.ai platform

As my understanding now using the Camera is not really necessary, as we mostly talking about use cases like chat applications.. I can imagine that they apply very well to a live chatroom written in ReactNative

<img src="https://user-images.githubusercontent.com/24992535/83751861-d98d9b80-a667-11ea-8b5f-74d93f59aa65.png" width="450" />

https://wit.ai/docs/recipes#categorize-the-user-intent

<img src="https://user-images.githubusercontent.com/24992535/83752046-25404500-a668-11ea-8c62-bc9706c30c4c.png" width="450" />

https://wit.ai/docs/recipes#do-sentiment-analysis

The chatroom will send information via [HTTP](https://wit.ai/docs/http/20200513) to the Wip.ai api, we can easily integrate it in the app using the [nodejs package](https://github.com/wit-ai/node-wit)

We have [several entities](https://wit.ai/docs/built-in-entities/20180601) available, as you send to their the `string` of text.. 

https://wit.ai/docs/http/20200513#post__entities__entity_keywords_link

```
  $ curl -XPOST 'https://api.wit.ai/entities/favorite_city/keywords?v=20200513' \
  -H "Authorization: Bearer $TOKEN" \
  -H 'Content-Type: application/json' \
  -d '{"keyword": "Brussels",
       "synonyms": ["Brussels", "Capital of Europe"]}'
```
based on the type of entity they will give you a result/response

```json
{
  "id": "57475251-ba5a-412b-85ec-3ab6f778d6fa",
  "name": "favorite_city",
  "roles": ["favorite_city"],
  "lookups": ["free-text", "keywords"],
  "keywords": [
    {"keyword": "Brussels",
     "synonyms": ["Brussels",
                  "Capital of Europe"]},
    {"keyword": "Paris",
     "synonyms": ["Paris",
                  "City of Light",
                  "Capital of France"]},
    {"keyword": "Seoul",
     "synonyms": ["Seoul",
                  "서울",
                  "Kimchi paradise"]}
  ]
}
```

No, need to to this with the [nodejs library](https://github.com/wit-ai/node-wit), but still useful to understand where are the docs

@ProBeta1 we need to find an interesting use case, easy and quick to implement as we could still submit a MVP for Deadline 5:00pm EDT Jun 24, 2020

@ProBeta1 even if they have relatively [large amount of entities](https://wit.ai/docs/built-in-entities/20180601), that can be used to extract information... I see no reason why somebody would download yet another chat app to have some smart autocomplete functionality...

But for sure it would be great using it in an existing app to extrapolate information from the conversation and do smart things with it

Maybe having an app with voice recognition to control your home, and using on the side wit.ai to idetify commands ... ??...

**Comment by renanmav** [comment]
Is there any scope related to which ML model we wanna to build? What do we like to recognize?

**Comment by renanmav** [comment]
Here are some common thigs we can do with wit.ai https://wit.ai/docs/recipes

**Comment by fabriziobertoglio1987** [comment]
Hello @renanmav Thanks a lot 

I went to the facebook hackathon [website](https://fbai2.devpost.com/?ref_content=online-hackathons&ref_feature=challenge&ref_medium=facebook-channel) and now I remember the scope:

>Build AI natural language interactions with Wit.ai
>submit a solution featuring natural language interactions that leverage the Wit.ai platform

As my understanding now using the Camera is not really necessary, as we mostly talking about use cases like chat applications.. I can imagine that they apply very well to a live chatroom written in ReactNative

<img src="https://user-images.githubusercontent.com/24992535/83751861-d98d9b80-a667-11ea-8b5f-74d93f59aa65.png" width="450" />

https://wit.ai/docs/recipes#categorize-the-user-intent

<img src="https://user-images.githubusercontent.com/24992535/83752046-25404500-a668-11ea-8c62-bc9706c30c4c.png" width="450" />

https://wit.ai/docs/recipes#do-sentiment-analysis

The chatroom will send information via [HTTP](https://wit.ai/docs/http/20200513) to the Wip.ai api, we can easily integrate it in the app using the [nodejs package](https://github.com/wit-ai/node-wit)

We have [several entities](https://wit.ai/docs/built-in-entities/20180601) available, as you send to their the `string` of text.. 

https://wit.ai/docs/http/20200513#post__entities__entity_keywords_link

```
  $ curl -XPOST 'https://api.wit.ai/entities/favorite_city/keywords?v=20200513' \
  -H "Authorization: Bearer $TOKEN" \
  -H 'Content-Type: application/json' \
  -d '{"keyword": "Brussels",
       "synonyms": ["Brussels", "Capital of Europe"]}'
```
based on the type of entity they will give you a result/response

```json
{
  "id": "57475251-ba5a-412b-85ec-3ab6f778d6fa",
  "name": "favorite_city",
  "roles": ["favorite_city"],
  "lookups": ["free-text", "keywords"],
  "keywords": [
    {"keyword": "Brussels",
     "synonyms": ["Brussels",
                  "Capital of Europe"]},
    {"keyword": "Paris",
     "synonyms": ["Paris",
                  "City of Light",
                  "Capital of France"]},
    {"keyword": "Seoul",
     "synonyms": ["Seoul",
                  "서울",
                  "Kimchi paradise"]}
  ]
}
```

No, need to to this with the [nodejs library](https://github.com/wit-ai/node-wit), but still useful to understand where are the docs

@ProBeta1 we need to find an interesting use case, easy and quick to implement as we could still submit a MVP for Deadline 5:00pm EDT Jun 24, 2020

@ProBeta1 even if they have relatively [large amount of entities](https://wit.ai/docs/built-in-entities/20180601), that can be used to extract information... I see no reason why somebody would download yet another chat app to have some smart autocomplete functionality...

But for sure it would be great using it in an existing app to extrapolate information from the conversation and do smart things with it

Maybe having an app with voice recognition to control your home, and using on the side wit.ai to idetify commands ... ??...

**Comment by cristianoccazinsp** [comment]
@fabriziobertoglio1987 does that mean updating RNCamera native code to support video/image streaming to a server? Or should that happen entirely from JS?

**Comment by fabriziobertoglio1987** [comment]
@cristianoccazinsp yes, it would entirely happes from JS relatively easy with their [nodejs package](https://github.com/wit-ai/node-wit)

and this are the [prizes](https://fbai2.devpost.com/?ref_content=online-hackathons&ref_feature=challenge&ref_medium=facebook-channel) 

![image](https://user-images.githubusercontent.com/24992535/83778549-26cf3480-a68b-11ea-8255-fe93e7e425f9.png)

I understand now the real objective of this Facebook Hackathon and of the Wit.ai platform

>Build AI natural language interactions with Wit.ai

But there are still applications for react-native-camera, as we can use our `Text Recognition` functionalities to build the application and then use js to do the `natural language interactions`

as anticipated in my https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-638799238 wit.ai has many pre-built entities which allows you to automatically extrapolate information and get ai answer (like when talking with a computer robot) 

And it is very easy to implement, no need to build anything, you just send the information to their api and you receive the answer via json api

For example the [`GET /message` endpoint](https://wit.ai/docs/http/20200513#get__message_link)

>Returns the extracted meaning from a sentence, based on the app data. Note that you may use JSONP to do cross-domain/cross-origin requests.

**REQUEST**
> GET https://api.wit.ai/message
```
$ curl -XGET 'https://api.wit.ai/message?v=20200513&q=how%20many%20people%20between%20Tuesday%20and%20Friday' \
      -H "Authorization: Bearer $TOKEN"
```
**RESPONSE**
```
{
    "text": "how many people between Tuesday and Friday",
    "intents": [
      {
        "id": "1701608719981716",
        "name": "inquiry",
        "confidence": 0.8849
      }
    ],
    "entities": {
      "metric:metric": [
        {
          "id": "3701487719281796",
          "name": "metric",
          "role": "metric",
          "start": 9,
          "end": 15,
          "body": "people",
          "value": "metric_visitor",
          "confidence": 0.9231,
          "entities": []
        }
      ],
      "wit$datetime:datetime": [
        {
          "id": "1701608719981711",
          "name": "wit$datetime",
          "role": "datetime",
          "start": 16,
          "end": 42,
          "body": "between Tuesday and Friday",
          "confidence": 0.9541,
          "entities": [],
          "type": "interval",
          "from": {
            "grain": "day",
            "value": "2020-05-05T00:00:00.000-07:00"
          },
          "to": {
            "grain": "day",
            "value": "2020-05-09T00:00:00.000-07:00"
          },
          "values": [
            {
              "type": "interval",
              "from": {
                "grain": "day",
                "value": "2020-05-05T00:00:00.000-07:00"
              },
              "to": {
                "grain": "day",
                "value": "2020-05-09T00:00:00.000-07:00"
              }
            },
            {
              "type": "interval",
              "from": {
                "grain": "day",
                "value": "2020-05-12T00:00:00.000-07:00"
              },
              "to": {
                "grain": "day",
                "value": "2020-05-16T00:00:00.000-07:00"
              }
            },
            {
              "type": "interval",
              "from": {
                "grain": "day",
                "value": "2020-05-19T00:00:00.000-07:00"
              },
              "to": {
                "grain": "day",
                "value": "2020-05-23T00:00:00.000-07:00"
              }
            }
          ]
        }
      ]
    }
  }
```

Their api returns different type of informations called [entities](https://wit.ai/docs/built-in-entities/20180601), so to have a quick understanding of the type of information that we can extract... we can just simply check out those entities...

For example you can also  [retrieve the meaning of an audio wave](https://wit.ai/docs/http/20200513#post__speech_link)

I think each entity is a different statistical model used to extrapolate information from your audio wave or your string... I think witai is very easy to use and there is no need for ML developer, we just need a mobile client app.. 

it is 100% react-native

**Comment by zejiran** [comment]
I have two ideas:
- A framework for making interactive webpages with chatbot.
- A platform for scanning food and obtaining important data about it. User can make food orders from the app and require specific information talking with the wit.ai chatbot. First, they send a picture on the chat of my plate of food, and the bot later ask for more information. Food industries can promote their products there and also connect order apps with it. Recover the cultural legacy that food brings

**Comment by ProBeta1** [comment]
Alright devs , I got a fresh idea for this hackathon, which holds a true potential for a real life app as well . So here it is : 

App Name: **BetterHalf Buddy**( tentative )

Yeah , you read it right . There are many messaging apps in the market currently , but this one would be just one on one app , means , you can use it to just message one other person . It will have all the features like whatsapp has , text and file sharing , but here is what distinguishes it : 

- Voice controlled update delivery to other person : Eg - "Tell Bob to pick me up at 5pm from my office today "
- Special gestures , eg - "Wake up Alice at 5am tomorrow "
- Send pictures at one command , eg : " take a picture now and send it to Alice "
- Set the other person's app images and displays
- Book third party services , eg : "Book a table for two at MacD tonight at 8pm "
- Emergency actions .
- You cant chat with multiple better halves through this , sadly :( 

If this idea sounds cool enough , we can discuss more over it , I can give lot more feature descp !

**Comment by fabriziobertoglio1987** [comment]
Stream the video and analyze the audio 

https://wit.ai/docs/http/20200513#post__speech_link

>Retrieve the meaning of an audio wave

>Returns the meaning extracted from an audio file or stream. We do recommend you to stream the audio input as it will reduce the latency, hence improve the user experience.

Kid dash cam
![image](https://user-images.githubusercontent.com/24992535/83867858-5ed98480-a72a-11ea-9dec-687d28cf5fe7.png)

Car dash cam
![image](https://user-images.githubusercontent.com/24992535/83868112-a4964d00-a72a-11ea-8a60-25ab0a206e02.png)

Don't know... but there are many applications, considering that you can easily use voice recognition to convert audio in string

**Comment by renanmav** [comment]
So, let’s close this for ideas and create an election with due date? (1 ~ 2 days)

**Comment by ProBeta1** [comment]
Yeah , @fabriziobertoglio1987  you may create a new issue with the topics and we can then comment our fav ones there !

**Comment by ProBeta1** [comment]
> I have two ideas:
> 
> * A framework for making interactive webpages with chatbot.
> * A platform for scanning food and obtaining important data about it. User can make food orders from the app and require specific information talking with the wit.ai chatbot. First, they send a picture on the chat of my plate of food, and the bot later ask for more information. Food industries can promote their products there and also connect order apps with it. Recover the cultural legacy that food brings

We do have some sites doing the first part , like Crisp , and they are doing it quite well . And second idea sounds nice but its a bit generic IMO .

**Comment by Epeagbas** [comment]
Sounds good

**Comment by saravananselvamohan** [comment]
Hi Team. Glad to have interesting ideas from everyone. Just I like to picturize the idea I have in mind.

Tons of information have hidden under unstructured data. Let's leverage the unstructured data using text mining techniques and users can access the prior information with simple questions to the chatbot.

**Simple Use Case:**
We can feed all the Wikipedia data to the bot, and directly we can ask questions to the bot and bot answers to questions with its prior knowledge based on the dataset.

**Advanced Use Case:**
In Healthcare sectors, Researchers need to go through a lot of information in the research papers where they spend a lot of time. If we are able to feed all the research data to the bot and able to get prior answers for questions, it would be greatly helpful to them. I can understand the point we cannot accept errors here.

In simple words, It can be implemented in any industry where people having lots of information in the text can fed data to the bot, and get answers for the questions they have.

**Comment by fabriziobertoglio1987** [comment]
discussion moved to https://github.com/fabriziobertoglio1987/hackathon-team/issues/8

**Comment by fabriziobertoglio1987** [comment]
I updated readme and added a [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

I will register a team in 1 week and I have already a product built. Please review the [guides here to be part of my team](https://github.com/fabriziobertoglio1987/hackathon-team/blob/master/projects/virtual-assistant.markdown) 

DEADLINE is 24 June so we need to register in 1 week. 

If you want to built a different project, you can add it to the readme in the [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

Thanks. Have a good week. Fabrizio
