### ISSUE TITLE
Technical Requirements

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#11]
React Native App with

1) Facebook Authentication
2) Facebook Graph API
3) Wit.AI API

**Not Priorities**

4) Voice Recognition
5) Firebase live chatroom

Please help me figure out how to build this :smiley:

**Comment by saravananselvamohan** [comment]
For Voice Recognition, We have an api from wit.ai to integrate with. We can architect voice recognition part in React Native App

**Comment by fabriziobertoglio1987** [comment]
@saravananselvamohan I know, but I rather do voice recognition locally on the device as using that endpoint will make the app slower

**Comment by fabriziobertoglio1987** [comment]
@saravananselvamohan  I knew about that endpoint, but I tought of using VoiceRecognition for the [chat functionalities](https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-639347880)

but I think you are right, we could implement those functionalities later

**Comment by ProBeta1** [comment]
So in the first phase of our project , what we would be coding is authenticating a FB user and using their voice commands to convert into text and show it on the screen , right ?
The next phase would be to implement the one-on-one chatting feature.

**Comment by ProBeta1** [comment]
[Link of tech specs Docs](https://docs.google.com/document/d/1mhWSdQCEuDWyCFlAztkG8FBoIFb-AY2Wolg1lTGVuH0/edit?usp=sharing)

**Comment by fabriziobertoglio1987** [comment]
Thanks @ProBeta1  Voice recognition only later on. Not now. This is the [order of functionalities](https://github.com/fabriziobertoglio1987/hackathon-team/issues/11#issue-632583888)

@ProBeta1 please use [markdown](https://guides.github.com/features/mastering-markdown/) for the docs and follow the below guidelines (each feature will have its own card in this kanban board and an issue). Thanks a lot

**IMPORTANT UPDATE**

I'm building the above discussed application. We can change it as by your requirement later on, but I want to start working as I want to submit something for the first round ending Deadline 5:00pm EDT Jun 24, 2020 and I can only work during the weekends

I'm organizing the work like this:

1) I'm building the wireframe and the more complex functionalities, so that other developer can work on the other more easy features/screens (like design, screens, navigation...etc...)
2) We have a separate [private repository](https://github.com/fabriziobertoglio1987/alex) with a separate [private kanban board](https://github.com/fabriziobertoglio1987/alex/projects/1). I need the repository to be private for practicality (I'm not hiding keys, password etc..). The developers can write pull request to close the cards/issues opened in the [private kanban board](https://github.com/fabriziobertoglio1987/alex/projects/1)

3) The following [Virtual Assistant AI and Chatroom `kanban board`](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2) is public and should be used to request 

- **FEATURES**
- **BUG FIXES**

But please be very specific and clear about those... so that we can create a similar task in the private repository and assign it to a developer

When you create a new card, create an issue as below displayed (Convert to issue)

![image](https://user-images.githubusercontent.com/24992535/83964234-d387fc80-a8ab-11ea-839c-735e566591d9.png)

Then give a clear requirement to the developer..

Lets start having **a card** for every **feature** in the mobile app and collect a clear requirement, so that we can start assigning the tasks to the different developers.

Additionally Issues for this project are tagged with [a specific Label](https://github.com/fabriziobertoglio1987/hackathon-team/labels/Virtual%20Assistant%20AI%20and%20Chatroom).

[Please help me posting on **Facebook** javascript groups](https://github.com/fabriziobertoglio1987/hackathon-team/issues/4) and any other chatroom to find developers, as there is much work to do.. 

Thanks
Fabrizio

**Comment by ProBeta1** [comment]
I cant access the private repo !

**Comment by fabriziobertoglio1987** [comment]
@ProBeta1  yes it is private. I need to invite you first

Lets discuss in the issue in the [Kanban board](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2) that you want to work on.. 

Thanks

**Comment by fabriziobertoglio1987** [comment]
I updated readme and added a [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

I will register a team in 1 week and I have already a product built. Please review the [guides here to be part of my team](https://github.com/fabriziobertoglio1987/hackathon-team/blob/master/projects/virtual-assistant.markdown) 

DEADLINE is 24 June so we need to register in 1 week. 

If you want to built a different project, you can add it to the readme in the [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

Thanks. Have a good week. Fabrizio
