### ISSUE TITLE
Voice recognition

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#12]
The user says to his phone to activate voice recognition

"Alex"    

Then the user sends the app the following question

"Where can I have dinner with Mike Labroski Tonight at 9:00 in New York City Central Park?"

The Facebook API to retrieve the list of restaurants will be built in separate task https://github.com/fabriziobertoglio1987/hackathon-team/issues/20

The Wit AI AP will be built with https://github.com/fabriziobertoglio1987/hackathon-team/issues/21 and https://github.com/fabriziobertoglio1987/hackathon-team/issues/26

This task only focus on installing and testing the voice recognition library:
https://github.com/react-native-community/voice

**Comment by LoopGlitch26** [comment]
Can you tell me about what to do under this? I can try to make the voice recognition part. I'd appreciate help and guidance too.

**Comment by fabriziobertoglio1987** [comment]
@LoopGlitch26 

Do you have JavaScript experience?
check the instructions for installation and setup https://github.com/react-native-community/voice

**Comment by LoopGlitch26** [comment]
> @LoopGlitch26
> 
> Do you know JavaScript?
> check the instructions for installation and setup https://github.com/react-native-community/voice
> 
> On 09/06/20 00:13, Bravish Ghosh wrote:
> 
> > Can you tell me about what to do under this? I can try to make the voice recognition part. I'd appreciate help and guidance too.
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.

Yeah, sure I will give it a try and let you know the results.

**Comment by fabriziobertoglio1987** [comment]
Thanks @LoopGlitch26 let me invite you to the repository.

Are you sure you want to take over this task? 
I later categorized it as non essential, as I am worried of the following:

1) Voice Recognition will not work correctly or misinterpret the user
2) The above library has a big number of open issues and bugs

I tough chat is easier and we avoid missing the due date which is already close, so I put this voice recognition functionality down on the bottom of the open [kanban board](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2)

I put on top all the Facebook Functionalities like issue https://github.com/fabriziobertoglio1987/hackathon-team/issues/20

as Facebook will be happy that we use their API ... and the experience will be useful for the next hackathon in August

If we have time we still can work on this

Let me know your choice, I'll try to assist you 
Thanks
Fabrizio

**Comment by LoopGlitch26** [comment]
Ok I see your point. It's always wise to use facebook API rather than this. But we can give it a short. Thanks for assigning

**Comment by LoopGlitch26** [comment]
But we can keep our priorities to the better issues which have the use of facebook APIs

**Comment by fabriziobertoglio1987** [comment]
yes, let me know if you have any issues

don't use facebook authentication, it will not work for you because I did not add you to the facebook developer team yet

set up your environment
https://reactnative.dev/docs/environment-setup

make sure that the AwesomeApp from the above instructions works

then install the dependencies as by instructions
https://github.com/react-native-community/voice

read very well those guide, but You should not to the linking or manual installation as we are using react native 0.62.

But read all the instructions as they make examples and explain how to set up the permissions on the bottom of the guide, even if are essential steps

they also have an example folder at https://github.com/react-native-community/voice/tree/master/example

so if you clone 

```
git clone https://github.com/react-native-community/voice
cd voice
cd example
yarn install
yarn start
yarn react-native run-android
```
you should be able to run their example. this is useful if you are having issues installing it in our project

so you see if they example works

if it does you check the settings that you are missing in our project

contact me here for any issue

but don't invest too much time on this task 

Maximum 30-40 minutes.. .if you see that configuring this is too hard

the facebook functionalities are relatively easy to do because I already configured authentication, and you just need to write a fetch get request

**Comment by fabriziobertoglio1987** [comment]
@LoopGlitch26 do you have an update? Do you need some help?

**Comment by fabriziobertoglio1987** [comment]
@LoopGlitch26 we are discussing in https://github.com/fabriziobertoglio1987/hackathon-team/issues/17#issuecomment-642492457 and this issue moved from low to high priority.. For this reason I need your feedback and please tell use if you need some help

maybe @saravananselvamohan @ProBeta1 @zejiran @renanmav can give you some help. Thanks

**Comment by LoopGlitch26** [comment]
I am not on my laptop currently. Once I get back to my working laptop in
some hours I'll let you know the problems I am facing in the react voice
framework. So far I've not tried much as you said not to give it too much
time.

**Comment by fabriziobertoglio1987** [comment]
sorry @LoopGlitch26 I need to assign you to another issue.

based on the updates from https://github.com/fabriziobertoglio1987/hackathon-team/issues/17 this issue now has maximum priority.

I need to build this feature tomorrow, otherwise we need to plan for building alternative type of application.

I will assign you another issue this afternoon.
Let me know the progress you did on this and please give share with me all the information you collected and your opinion. Did you read the documentation on the library and the open issues? 

Thanks a lot and sorry
