### ISSUE TITLE
Set up IOs Facebook Authentication

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#14]
Instructions [here](https://github.com/facebook/react-native-fbsdk#32-ios)

>3.2 iOS

>Follow steps 3 and 4 in the Getting Started Guide for Facebook SDK for iOS.

https://developers.facebook.com/docs/ios/getting-started/?sdk=cocoapods

**Comment by renanmav** [comment]
I would like to do this one. Do you already have the RN App so I can start working on it?

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot. I'll invite you to the github repository.

I need your facebook account to add you to the Facebook Developers so you can do testing and configuration.

Thanks
Fabrizio

**Comment by renanmav** [comment]
https://www.facebook.com/mavrenan

**Comment by fabriziobertoglio1987** [comment]
You need to accept the facebook invitation to the team.
https://github.com/fabriziobertoglio1987/alex
https://developers.facebook.com/apps/254305266005405/dashboard/

1) Test the android app facebook authentication with your account
2) Set up the iOS settings as described here 
Instructions [here](https://github.com/facebook/react-native-fbsdk#32-ios)

>3.2 iOS

>Follow steps 3 and 4 in the Getting Started Guide for Facebook SDK for iOS.

https://developers.facebook.com/docs/ios/getting-started/?sdk=cocoapods

Contact me if you have an issues

**Comment by renanmav** [comment]
I didn’t get the invitation to the facebook app

**Comment by fabriziobertoglio1987** [comment]
On Facebook notifications

**Comment by fabriziobertoglio1987** [comment]
@renanmav do you have an update on this task? Do you need some help? Thanks

**Comment by renanmav** [comment]
Yeah, I opened an issue within alex repo, can you take a look?

**Comment by fabriziobertoglio1987** [comment]
you need to run `react-native run-ios`

**Comment by fabriziobertoglio1987** [comment]
https://github.com/fabriziobertoglio1987/alex/issues/1#issuecomment-643579658

**Comment by fabriziobertoglio1987** [comment]
I believe the guide is wrong, we don't use swift and installing this dependency should not require us to do any setting in native code except adding some variables 

do this settings from https://developers.facebook.com/docs/ios/getting-started/?sdk=cocoapods

![image](https://user-images.githubusercontent.com/24992535/84561976-0e2ce180-ad51-11ea-957f-54144da76d57.png)

test the app, if it does not work (or error message does not change), research their issue

I found this https://github.com/facebook/react-native-fbsdk/issues/762

but I don't believe that you need to change the code, I believe he removed the instructions for Objective C because you just need to add those variables from the screnshot

let me know
thanks

**Comment by fabriziobertoglio1987** [comment]
@javiershaka Unluckily we could not find a use case for witai and the Facebook Graph API.
For this reason I am closing this issue and you should not work on it anymore.

As we can not retrieve any relevant information from Facebook using wit.ai, there is no need to send message, share etc... 

All this operation require Facebook review process which takes many days and we are very in trouble with deadline right now. Thanks and Sorry
