### ISSUE TITLE
Retrieve Chat History

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#17]
We have the Token and we need to retrieve the user Messanger chat history

https://developers.facebook.com/docs/messenger-platform

**Comment by fabriziobertoglio1987** [comment]
@saravananselvamohan @CasCard @animeshmohanty can you give me some Feedback? Are you willing to work on this? Could you write me 3-4 lines to better understand how will you build the functionality? Thanks

**Comment by saravananselvamohan** [comment]
Hi, @fabriziobertoglio1987. To retrieve chat history, From the developer guide, it was quoted. we can use send API to retrieve messages. 

https://developers.facebook.com/docs/graph-api/reference/conversation/#conversation---conversation-id-
https://developers.facebook.com/docs/messenger-platform/reference/send-api/#request
Correct me, if I am in the wrong path

**Comment by animeshmohanty** [comment]
Hi @fabriziobertoglio1987 . I do think the best way to retrieve chat history with an API, but i think only the twillio API and the messenger for devs API give us that advantage as of now as correctly said by @saravananselvamohan (I might not know about others) or we can just, you know retrieve it by saving it in a db i would suggest something like Firebase, so if its a chatbot and every time the bot responds to an user's message, we have to save the messages in the database and we can retrieve it with a timestamp. Although i need to go through some sources to confirm it being possible, I believe its doable.

OR: https://www.twilio.com/docs/sms/tutorials/how-to-retrieve-and-modify-message-history

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot @saravananselvamohan 


#### POINT 1 - Retrieve a list of the latest conversations of a user with his friends through the Facebook API (Screenshot below).

It is not possible with Facebook API. We could find a workaround to do it but it is not worth investing that time.

Very good analysis @animeshmohanty 

#### POINT 2 - As Point 1) is not possible, we can just skip this functionality. 

As mentioned in https://github.com/fabriziobertoglio1987/hackathon-team/issues/16 I am assigned to build the Firebase Chat. 

I would avoid calling Facebook and having to build complex features like @animeshmohanty explained us in his post. @animeshmohanty is right, it is relatively complex functionality compared to a voice recognition application.

This makes chat less interesting then voice recognition https://github.com/fabriziobertoglio1987/hackathon-team/issues/12

Few Users will migrate from messanger to a new app, just to use a couple of AI functionalities that mostly will spam them with advertisement of restaurants, places to visits (this is what we can do with Facebook API) etc..

While if we have a solid Voice Recognition, we can build functionalities similar to Alexa for a phone and integrate them with the Facebook API. Users can still send messages to another one using Facebook API and voice control https://github.com/fabriziobertoglio1987/hackathon-team/issues/27

If you agree I would close this issue and give priority to Voice Recognition functionality.

BUT I would like to have @animeshmohanty and @saravananselvamohan **honest** feedback on this :smiley: Thanks a lot for the very good feedback :smiley: 

<img src="https://user-images.githubusercontent.com/24992535/84359619-2d990280-abc9-11ea-8126-8f6f00c71072.png" width="200" />

**Comment by animeshmohanty** [comment]
I think i am cool with it @fabriziobertoglio1987 . Afterall we do not want a high compexity factor which is cumbersome. If otherwise, I am cool with it too.
