### ISSUE TITLE
Facebook Event API

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#19]
One user sends chat message to another user

"Tomorrow is Mike Birthday"

Wit.AI retrieve this information from this massage using functionalities already built in https://github.com/fabriziobertoglio1987/hackathon-team/issues/21

More info on Wit.AI setting at https://github.com/fabriziobertoglio1987/hackathon-team/issues/20 and https://github.com/fabriziobertoglio1987/hackathon-team/issues/26

The app automatically join the event on facebook with their api (facebook events acts like google calendar)

https://developers.facebook.com/docs/graph-api/reference/event/#Reading

**Comment by fabriziobertoglio1987** [comment]
@ProBeta1 I assign this task to you. Contact me for any help. Thanks a lot. :smiley:

**Comment by fabriziobertoglio1987** [comment]
@ProBeta1 can you give me some Feedback? Are you willing to work on this? Could you write me 3-4 lines to better understand how will you build the functionality? Thanks

**Comment by fabriziobertoglio1987** [comment]
Hello @LoopGlitch26 

I assigned you this task. Please contact me for any help and let me know your progress. Thanks

**Comment by fabriziobertoglio1987** [comment]
@LoopGlitch26 could you give me an update on this? Will you start working on this task on Saturday?
Thanks a lot.

**Comment by fabriziobertoglio1987** [comment]
@CasCard would you like to work with @LoopGlitch26 on this task? Thanks

**Comment by CasCard** [comment]
Yeah sure

**Comment by LoopGlitch26** [comment]
@fabriziobertoglio1987 I will start working on it now. I was unable to get some free time because of some issues, but I along with @CasCard 's help will be doing this work. Thanks.

**Comment by fabriziobertoglio1987** [comment]
@CasCard @LoopGlitch26 I just completed all the other difficult tasks and I am taking this task. Don't work on it. If you want to participate please find another task from the [Kanban](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2) board. Thanks

**Comment by fabriziobertoglio1987** [comment]
Facebook Events API allows us to read the user events, but not search, update, delete user events.
We can:
- Display the events created and joined on facebook from the user

We can not:
- join an event using our app voice commands
- create an event with our app voice commands
- invite somebody to an event (birthday) using our app voice commands
 - leave an event

This makes events api not a priority, as we can not build some sort of Voice Command Calendar based on Facebook, still we could do it with other APIs. I move this task to low priority.

![Screenshot from 2020-06-13 11-31-55](https://user-images.githubusercontent.com/24992535/84565446-82737f00-ad69-11ea-9dd9-5c7bf062dc5e.png)


![Screenshot from 2020-06-13 11-27-52](https://user-images.githubusercontent.com/24992535/84565377-fa8d7500-ad68-11ea-8a90-0cfe083645a3.png)

we could show a list of upcoming events to the user. 

![image](https://user-images.githubusercontent.com/24992535/84565401-30325e00-ad69-11ea-8459-8cf4d502ba5e.png)
