### ISSUE TITLE
Facebook Places API

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#20]
A User writes this message:

"Where do you want to meet tonight to drink a Beer in New York?"

Wit.ai interprets the message with the already built functionality in https://github.com/fabriziobertoglio1987/hackathon-team/issues/21

1) Verify that we can build this with wit.ai
https://wit.ai/docs/http/20200513#get__message_link
`/message` endpoint is already built in our app with issue https://github.com/fabriziobertoglio1987/hackathon-team/issues/21

2) Call the Facebook API 
The app should use the Places and or Group api to give suggestions

https://developers.facebook.com/docs/places/web/search
https://developers.facebook.com/docs/react-native
https://developers.facebook.com/docs/groups-api/

**Comment by fabriziobertoglio1987** [comment]
@zejiran I saw that you are a proficient JavaScript Developer. I decided to assign this task to you. Please contact me for any issue. Thanks. :smiley:

**Comment by fabriziobertoglio1987** [comment]
@zejiran can you give me some Feedback? Are you willing to work on this? Could you write me 3-4 lines to better understand how will you build the functionality? Thanks

**Comment by zejiran** [comment]
I am checking right now that we can build this with wit.ai. Today I will learn about calling APIs, for making the necessary code to call the Facebook API. After that, I would share the repository here.

**Comment by fabriziobertoglio1987** [comment]
AMAZING @zejiran @vedantiitkgp is our AI/ML Expert and he working on wit.ai 

You should coordinate with him and share you finding on wit.ai on the issue https://github.com/fabriziobertoglio1987/hackathon-team/issues/26

Then keep researching for on the Facebook API, if you find some other applications for the Facebook API, you open a task in our [KanBan board](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2)

Actually I noticed that I included the wrong link, we are not using the Android SDK in out app (so ignore the [previous link](https://developers.facebook.com/products/places))
https://developers.facebook.com/docs/places/web/search
https://developers.facebook.com/docs/react-native/graph-api

Also some more info here, but I would stick to the graphql api above.
https://developers.facebook.com/docs/react-native
https://github.com/facebook/react-native-fbsdk

You should know, for everything you request from Facebook you need specific user authorication

https://developers.facebook.com/docs/facebook-login/permissions/overview

Currently we are asking for basic permission in our facebook login, the token we get can only be user for basic things

We need to add permissions here 
https://github.com/facebook/react-native-fbsdk#requesting-additional-permissions-with-login-manager

but for now don't worry about that, just use their graphql explorer to test those api request with some token

https://developers.facebook.com/tools/explorer/

Thanks
Bye

**Comment by fabriziobertoglio1987** [comment]
I added you to the facebook app developer team

![image](https://user-images.githubusercontent.com/24992535/84413472-f3535380-ac10-11ea-81da-17a9f02f5c3c.png)

The name of the app is alex

**Comment by zejiran** [comment]
<img width="976" alt="Captura de Pantalla 2020-06-11 a la(s) 11 27 31 a  m" src="https://user-images.githubusercontent.com/30379522/84413678-95097f00-abd6-11ea-8949-af74667beaea.png">

**Comment by zejiran** [comment]
I can't change our KanBan board. I think that we could see the price of the product with wit.ai and recommend places to the user acording to the cost.

**Comment by fabriziobertoglio1987** [comment]
Awesome.. 

https://wit.ai/docs/built-in-entities/20180601
![image](https://user-images.githubusercontent.com/24992535/84415542-344c6780-ac13-11ea-919b-dc7040292a33.png)

I think the main issue is not building the functionality, I am more worried of obtaining the authorization from Facebook to use this type of data ... 

So if there is approval process, we need to initialize it soon as it may take 1 week and could be one of the reasons for disqualifications 

https://developers.facebook.com/docs/facebook-login/permissions/
https://developers.facebook.com/docs/facebook-login/permissions/review

We have a new member @gittycoder01 that does not have programming background an maybe be interested on working on this

I'll create a new task for him in the KanBan Board

**Comment by fabriziobertoglio1987** [comment]
I sent you invite to join our github repo Alex. It's the mobile app.
To set up development environment follow carefully this guide

select react native quickstart
https://reactnative.dev/docs/environment-setup

![image](https://user-images.githubusercontent.com/24992535/84417388-d8371280-ac15-11ea-8d85-32a17cc69529.png)

If you don't want to set up the development environment, you can write the code in javascript and I will integrate it in the application.

If you want you can also focus on research like now and just analyze the applications of witai and facebook api

As you prefer.

Thanks
Fabrizio

**Comment by zejiran** [comment]
Updates: code for consume wit API ->
```javascript
const fetch = require('node-fetch');

const options = {
  method: 'GET',
  headers: {
    'Content-Type': 'application/json', 'Authorization' : 'Bearer WXTP7M5QK7IMHQWNHLZ3F33O7YSR2NSM'
  }
};

const urlWit = 'https://api.wit.ai/message?v=20200611&q=Where%20can%20we%20meet%20in%20New%20York%20for%20a%20drink%3F';

const getUrl = (url, options) => fetch(url, options);

const x = getUrl(urlWit, options)
    .then(res => res.json())
    .then((json) => {
      return json
    });

x.then(x => console.log(x))

**Comment by fabriziobertoglio1987** [comment]
https://github.com/fabriziobertoglio1987/alex/commit/fa5fae93a638f6258a3e9b5f8f62cca5511b2bff

https://github.com/fabriziobertoglio1987/hackathon-team/issues/21

**Comment by zejiran** [comment]
> [fabriziobertoglio1987/alex@fa5fae9](https://github.com/fabriziobertoglio1987/alex/commit/fa5fae93a638f6258a3e9b5f8f62cca5511b2bff) and [fabriziobertoglio1987/alex@7041ea2](https://github.com/fabriziobertoglio1987/alex/commit/7041ea273a6d1f1ef9daf8ab3e23746fad9b3279) and #21
> 
> As previously explained, this functionality already was already built 1 week ago

Yes, it was just for testing and understanding purposes.

**Comment by zejiran** [comment]
GET Food places structure
</search?type=place&q={$PLACE, $FOOD
<img width="976" alt="Captura de Pantalla 2020-06-11 a la(s) 2 10 21 p  m" src="https://user-images.githubusercontent.com/30379522/84429596-07398e00-abee-11ea-97d1-69adb5a272a2.png">
}&fields=name,website&categories=["FOOD_BEVERAGE"]>
-> Example
https://graph.facebook.com/search?type=place&q=New York, beer&fields=name,website&categories=["FOOD_BEVERAGE"]

**Comment by fabriziobertoglio1987** [comment]
we need to get 2 information from witai

1) The place. Can we query only for the city or also for a place (for ex. [The Bronx](https://www.google.com/search?client=ubuntu&channel=fs&q=the+bronx+new+york+pub&ie=utf-8&oe=utf-8))? 

2) witai should recognize the user intent to search for a place

3) witai should recognize the category of place the user is searching for

4) witai should recognize the information (fields) the users wants to retrieve

5) we need to add additionaly query parameters to witai and facebook api to restrict the search and make it most relevant as possible

Awesome work. Thanks

**Comment by zejiran** [comment]
Added this to the app. 

<img width="976" alt="Captura de Pantalla 2020-06-12 a la(s) 8 46 27 p  m" src="https://user-images.githubusercontent.com/30379522/84557100-cb85ed80-aced-11ea-9f3e-29d8fec9eeca.png">

The user intent will be recognized as they are other intentions for the the different functionalities. Do not know how to recognize the information (fields) the users wants to retrieve, maybe it is implicit on the intent.

**Comment by zejiran** [comment]
I have set my development environment for React. What can I do now?

**Comment by fabriziobertoglio1987** [comment]
thanks @zejiran 

you can prepare a pull request to add api endpoint

include your functions inside https://github.com/fabriziobertoglio1987/alex/blob/master/src/lib/facebook/places.js

no need to run the react-native dev environment, you can just write them in js console and paste them in the file.

i'll be working all day on this. Thanks

**Comment by fabriziobertoglio1987** [comment]
I am already working on the screens to display the results from Facebook Places API https://github.com/fabriziobertoglio1987/hackathon-team/issues/39

This task has a high priority an needs to be completed for the 17th June

@zejiran Do you can do that? Thanks

You just need to send a pull request,  that adds the following function to this file https://github.com/fabriziobertoglio1987/alex/blob/master/src/lib/facebook/places.js

```javascript
// gets places from https://github.com/fabriziobertoglio1987/alex/blob/master/src/lib/facebook/places.js
async function getPlaces(parameters) {
   const response = await fetch("https://......");
   const json = await response.json();
   return json;
}
```

**Comment by fabriziobertoglio1987** [comment]
The Places API is deprecated and will be removed August 2020
![image](https://user-images.githubusercontent.com/24992535/84574327-0a777a00-ada6-11ea-8028-f9a5e7c3c250.png)

We can not use that api.
