### ISSUE TITLE
Wit.ai additional apis

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#26]
One user sends chat message to another user

"Tomorrow is Mike Birthday"
"Where do you want to meet tonight to drink a Beer in New York?"

Wit.AI retrieve this information from this massage using functionalities already built in https://github.com/fabriziobertoglio1987/hackathon-team/issues/21

API docs here
https://wit.ai/docs/http/20200513#get__message_link

I need assistance in understanding the informations that can be extracted from those 2 sentences.

1) Review configurations to do on the Wit.ai platforms, see:
https://wit.ai/docs/quickstart

2) Information that be extracted from those sentences
https://wit.ai/docs/built-in-entities/20180601

3) Api endpoint that we can call
https://wit.ai/docs/http/20200513

please do a very thougt review of those documents and application that we can build using 

https://developers.facebook.com/docs/graph-api/

**Comment by vedantiitkgp** [comment]
Hello @fabriziobertoglio1987  I am starting with this issue !

**Comment by fabriziobertoglio1987** [comment]
I am grateful @vedantiitkgp. I'm struggling right now. Please discuss with me and ask me any question.

This is a test request that uses the [`/message`](https://wit.ai/docs/http/20200513#get__message_link) endpoint. I already built it in feature https://github.com/fabriziobertoglio1987/hackathon-team/issues/21

The below curl request uses `/message` with string "Today is my Birthday"

```
curl \
 -H 'Authorization: Bearer AHJFYAZWCEPP6WBQXMGH356Y42AINKKT' \
 'https://api.wit.ai/message?v=20200611&q=Today%20is%20my%20Birthday'
```

please register at wit.ai and send me your username. I ll try to add you to my app.

But it is a good idea for you to register an app and start trying it out..
You could focus on Wit.AI configuration and model training as nobody know how to do that in our team

Thanks a lot
Fabrizio

**Comment by vedantiitkgp** [comment]
Oohk I am going through with the Wit.AI configuration and model training! By username are you referring Wit.ai username ?

**Comment by fabriziobertoglio1987** [comment]
vedantsaraswat
![image](https://user-images.githubusercontent.com/24992535/84386698-115d8b80-abf2-11ea-97b6-8aa0bea0f6e9.png)

**Comment by zejiran** [comment]
@vedantiitkgp check issue #20. We should work together. Right now, I am extracting with wit.ai specific information, from user message, to connect it with places APIs.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/fabriziobertoglio1987/hackathon-team/issues/20#issuecomment-643099983

**Comment by fabriziobertoglio1987** [comment]
Hello @Epeagbas I think you could also work on this task. You have not been replying to any message and you never participated in any conversation. Could you please tell us something? Thanks

**Comment by fabriziobertoglio1987** [comment]
@zejiran as discussed in https://github.com/fabriziobertoglio1987/hackathon-team/issues/26#issuecomment-642619481 I need your witai account name so that you can do the configurations for witai. I will work this weekend on the app and would like to add all those api requests and have alex app on witai already configured and trained. thanks

**Comment by zejiran** [comment]
This is my account name for wit.ai 'juansebastinalegraziga'. Today I will set up the react environment and see how I can help.

**Comment by fabriziobertoglio1987** [comment]
@zejiran I suggest you to not set the react-native environment. You can only work on the javascript apis and for that you don't need to get the environment running 

Just publish a pr that includes functions to do those api requests as said in:
https://github.com/fabriziobertoglio1987/hackathon-team/issues/20#issuecomment-643580034
