### ISSUE TITLE
Facebook Send Message

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#27]
@javiershaka 

The user will say to the app 

"alex"

Voice recognition activates - He send the following voice command:

"please send this message to my friend Micheal Pena" 

"Please Michael, switch off the light when you leave my apartment and clean up!"

a text message is delivered to facebook via this api to that user (facebook chat message):

https://developers.facebook.com/docs/messenger-platform/reference/send-api/#request

I will build the voice recognition functionality tomorrow https://github.com/fabriziobertoglio1987/hackathon-team/issues/12

The witai functionalities should be build in https://github.com/fabriziobertoglio1987/hackathon-team/issues/26 so please contact him for this functionalities, you don't need to work on the interpretation of the message `"please send this message to my friend Micheal Pena"` into an action of sending a message to facebook user

please send me your facebook account, I will add you to the facebook developer team.

**YOUR TASK**

Build the api request to facebook to send a message.

https://developers.facebook.com/docs/messenger-platform/reference/send-api/#request

Read our conversation https://github.com/fabriziobertoglio1987/hackathon-team/issues/20 to have more additional info

contact me for any issue in this conversation :smiley:

**Comment by javiershaka** [comment]
My facebook
www.facebook.con/javiershakas
While i'll be reading what you sent

**Comment by fabriziobertoglio1987** [comment]
I added you to the developers team

please start working on this

![image](https://user-images.githubusercontent.com/24992535/84563812-8057f300-ad5e-11ea-9096-08e24dcebe1c.png)

contact me for any of your questions in this discussion
thanks

**Comment by fabriziobertoglio1987** [comment]
@javiershaka please send me the http request. see more info at https://github.com/fabriziobertoglio1987/hackathon-team/projects/2

**Comment by javiershaka** [comment]
thanks for the infomation.
As I am new using this technology you will need a more time with me.
I will ask any questions that may arise.

**Comment by fabriziobertoglio1987** [comment]
please use the graph api explorer and build that request 

https://developers.facebook.com/docs/graph-api/explorer/ 

Thanks

**Comment by javiershaka** [comment]
Thanks, any questions i will still ask

**Comment by fabriziobertoglio1987** [comment]
@javiershaka Unluckily we could not find a use case for witai and the Facebook Graph API.
For this reason I am closing this issue and you should not work on it anymore.

As we can not retrieve any relevant information from Facebook using wit.ai, there is no need to send message, share etc... 

All this operation require Facebook review process which takes many days and we are very in trouble with deadline right now. Thanks and Sorry

**Comment by javiershaka** [comment]
thanks for your time.
whatever is offered to you there I am at your service.
