### ISSUE TITLE
Privace Policy

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [fabriziobertoglio1987/hackathon-team#29]
After reading [iubenda docs](https://www.iubenda.com/en/help/13561-privacy-policy-for-facebook-apps) it should be pretty streight forward

all instructions in the above link, you just post the url on facebook dashboard and iubenda will generate all required information

more discussion at https://github.com/fabriziobertoglio1987/hackathon-team/issues/28#issuecomment-643106092

@gittycoder01 we will work on this on the 16th of June together

**Comment by gittycoder01** [comment]
I'll take note on this. Good Day!
