### ISSUE TITLE
Idea Selection

### ISSUE THREAD

**Issue by ProBeta1** [fabriziobertoglio1987/hackathon-team#8]
- BetterHalf Buddy : [messaging app with voice controlled bot](https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-639347880)

- Audio analysis using video stream : [select one of these](https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-639405483)

- Food detail app : [here](https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-639268836)

- Questioning & Answering Chatbot: [check here](https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-639955154)

Comment in this thread what idea seems the best for the AI hackathon , and how would you contribute for it :) 

Deadline - 6th June , 5pm IST

**UPDATE : IF YOU DO NOT REACT TO ONE OF THE IDEAS AND NEITHER PROPOSE ONE OF YOUR OWN , YOU WOULD LOSE THE MEMBERSHIP FOR THIS FB AI HACKATHON SADLY**

@sibelius @ako1983 @Epeagbas @zejiran @vedantiitkgp @LoopGlitch26 @cristianoccazinsp

**Comment by renanmav** [comment]
React to this if you vote for **BetterHalf Buddy**

**Comment by renanmav** [comment]
React to this if you vote for **Audio analysis using video stream**

**Comment by renanmav** [comment]
React to this if you vote for **Food detail app**

**Comment by saravananselvamohan** [comment]
React to this if you vote for **Question & Answering Chatbot**

**Comment by LoopGlitch26** [comment]
Reading the better half buddy idea, I have an extension for that idea. 

# **BetterHalf Parter- A matchup AI **
 
Every Facebook user will be directed towards our app/website for a personality survey. Based on the survey and emotions of their activities in Facebook using AI, we can try to make a graphical representation of those variables and match the users (suggest the users) for dating with any gender they choose.

## Insights

This project will help in improving social interaction and communication. Nowadays there are a lot of social trafficking, mental problems and cyber crimes. To prevent such measures we have to ensure that our members are secured and under good mental health. Having a close friend/partner through this app will definitely help in decrease of such crimes. 
During this pandemic bizarre most of the audience is spending their time on social medias. Having such an app will help not only to find good buddies but also help to build a good mental health.

P.S- Idea open to constructive criticism

**Comment by zejiran** [comment]
> Reading the better half buddy idea, I have an extension for that idea.
> 
> # **BetterHalf Parter- A matchup AI**
> Every Facebook user will be directed towards our app/website for a personality survey. Based on the survey and emotions of their activities in Facebook using AI, we can try to make a graphical representation of those variables and match the users (suggest the users) for dating with any gender they choose.
> 
> ## Insights
> This project will help in improving social interaction and communication. Nowadays there are a lot of social trafficking, mental problems and cyber crimes. To prevent such measures we have to ensure that our members are secured and under good mental health. Having a close friend/partner through this app will definitely help in decrease of such crimes.
> During this pandemic bizarre most of the audience is spending their time on social medias. Having such an app will help not only to find good buddies but also help to build a good mental health.
> 
> P.S- Idea open to constructive criticism

Nice! So basically my partner is going to track and see statistics of my mental health analyzed through social media? If this works, it could help many people with depression for being saved by their buddies. Although I still don't understand how we are going to use wit.ai here or on the first version of the idea.

**Comment by LoopGlitch26** [comment]
> > Reading the better half buddy idea, I have an extension for that idea.
> > # **BetterHalf Parter- A matchup AI**
> > Every Facebook user will be directed towards our app/website for a personality survey. Based on the survey and emotions of their activities in Facebook using AI, we can try to make a graphical representation of those variables and match the users (suggest the users) for dating with any gender they choose.
> > ## Insights
> > This project will help in improving social interaction and communication. Nowadays there are a lot of social trafficking, mental problems and cyber crimes. To prevent such measures we have to ensure that our members are secured and under good mental health. Having a close friend/partner through this app will definitely help in decrease of such crimes.
> > During this pandemic bizarre most of the audience is spending their time on social medias. Having such an app will help not only to find good buddies but also help to build a good mental health.
> > P.S- Idea open to constructive criticism
> 
> Nice! So basically my partner is going to track and see statistics of my mental health analyzed through social media? If this works, it could help many people with depression for being saved by their buddies. Although I still don't understand how we are going to use wit.ai here or on the first version of the idea.

Wit.ai will be used to make the app/bot which will be responsible for direct interaction with the user . We can still brainstorm..

**Comment by zejiran** [comment]
Is it difficult to make an animated friendly assistant?

**Comment by ProBeta1** [comment]
A brief update , the BetterHalf Buddy app is not for Singles =P
Its not supposed to be a dating app , otherwise we would lose the original flow of the app's idea and we already have so many matching apps in the market.
Its only for the couples who are already in relationship, and yes , @zejiran and @LoopGlitch26 your ideas of assessing mental health of the better half is indeed very nice and we can work on that.

And bots only do the boring tasks , like automating restaurant booking etc. Both persons have to be humans for now !

**Comment by LoopGlitch26** [comment]
> A brief update , the BetterHalf Buddy app is not for Singles =P
> Its not supposed to be a dating app , otherwise we would lose the original flow of the app's idea and we already have so many matching apps in the market.
> Its only for the couples who are already in relationship, and yes , @zejiran and @LoopGlitch26 your ideas of assessing mental health of the better half is indeed very nice and we can work on that.
> 
> And bots only do the boring tasks , like automating restaurant booking etc. Both persons have to be humans for now !

Exactly! The idea I proposed was supposed to be an extension to this one..so that even singles can get connected with similar mentality humans through social media like Facebook etc which is nowadays flooded with fake accounts mostly, ending up trust of the users on the app.

**Comment by zejiran** [comment]
I think that it should not be limited to couples, but rather allows interaction between good friends or people who have mutual trust.

**Comment by cristianoccazinsp** [comment]
I don't have any good ideas to propose right now, but I'm willing to help
if I have free time :)

**Comment by fabriziobertoglio1987** [comment]
Thanks @cristianoccazinsp We absolutely need your help

**QUICK UPDATE**

Today I wanted to get a super quick Minimum Viable Product based on the [idea](https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-639347880) from @ProBeta1 

I wrote it with expo, the basic idea was having a Mobile app similar to Alexa that would do voice recognition and messanging and [implement similar functionalities](https://github.com/fabriziobertoglio1987/hackathon-team/issues/1#issuecomment-639347880)

1) Facebook API
https://docs.expo.io/versions/latest/sdk/facebook/
https://developers.facebook.com/docs/graph-api/overview

2)  Speech API
https://docs.expo.io/versions/latest/sdk/speech/

3) Wit.ai

Fact is that I noticed the following limitation of [expo-facebook](https://docs.expo.io/versions/latest/sdk/facebook/)

>The slight downside to this is that you can't customize which permissions your app requests from Facebook (like user_photos or user_friends)

Which means that we can not build this with expo, we need to authenticate users and ask several permission to use the Facebook API in combination with WIT.AI

So tomorrow I'll start a new React Native app based and start to implement the following features

1) Facebook Authentication
2) Facebook Graph API
3) Wit.AI API
4) Voice Recognition

The rest of the functionalities should not be too hard.
Last to be implemented would be Firebase chat.

**Comment by fabriziobertoglio1987** [comment]
**IMPORTANT UPDATE**

I'm building the above discussed application. We can change it as by your requirement later on, but I want to start working as I want to submit something for the first round ending Deadline 5:00pm EDT Jun 24, 2020 and I can only work during the weekends

I'm organizing the work like this:

1) I'm building the wireframe and the more complex functionalities, so that other developer can work on the other more easy features/screens (like design, screens, navigation...etc...)
2) We have a separate [private repository](https://github.com/fabriziobertoglio1987/alex) with a separate [private kanban board](https://github.com/fabriziobertoglio1987/alex/projects/1). I need the repository to be private for practicality (I'm not hiding keys, password etc..). The developers can write pull request to close the cards/issues opened in the [private kanban board](https://github.com/fabriziobertoglio1987/alex/projects/1)

3) The following [Virtual Assistant AI and Chatroom `kanban board`](https://github.com/fabriziobertoglio1987/hackathon-team/projects/2) is public and should be used to request 

- **FEATURES**
- **BUG FIXES**

But please be very specific and clear about those... so that we can create a similar task in the private repository and assign it to a developer

When you create a new card, create an issue as below displayed

![image](https://user-images.githubusercontent.com/24992535/83964234-d387fc80-a8ab-11ea-839c-735e566591d9.png)

Then give a clear requirement to the developer..

Lets start having **a card** for every **feature** in the mobile app and collect a clear requirement, so that we can start assigning the tasks to the different developers.

Additionally Issues for this project are tagged with [a specific Label](https://github.com/fabriziobertoglio1987/hackathon-team/labels/Virtual%20Assistant%20AI%20and%20Chatroom).

[Please help me posting on **Facebook** javascript groups](https://github.com/fabriziobertoglio1987/hackathon-team/issues/4) and any other chatroom to find developers, as there is much work to do.. 

Thanks
Fabrizio

**Comment by fabriziobertoglio1987** [comment]
As I am already building an app and I don't think it make sense building 2-3 apps for 1 hackathon.

I would say that we close this issue and we move from planning to delivery. 

If you want to build a different application in the future, you may open another Issue for discussing.

**Comment by fabriziobertoglio1987** [comment]
I updated readme and added a [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

I will register a team in 1 week and I have already a product built. Please review the [guides here to be part of my team](https://github.com/fabriziobertoglio1987/hackathon-team/blob/master/projects/virtual-assistant.markdown) 

DEADLINE is 24 June so we need to register in 1 week. 

If you want to built a different project, you can add it to the readme in the [project section](https://github.com/fabriziobertoglio1987/hackathon-team#projects---1-week-left-to-registration). 

Thanks. Have a good week. Fabrizio
